### ISSUE TITLE
Exynos GPU does not pass validation

### ISSUE THREAD

**Issue by tangobravo** [google/agi#1132]
It would be nice to get the S22 series supported - the latest Samsung "S" phone is usually the most common android device in US/UK/EU markets. There's still the Exynos / Snapdragon split between markets AFAIK.

Obviously with Android there's a very long tail so I'm not sure asking for GitHub issues to request device support is particularly useful...

**Comment by ttanatb** [comment]
Phones that launch with Android 12 should support AGI by default (which includes the S22 series)

If you're facing issues validating S22 & you have an Adreno GPU it might be due to this issue https://github.com/google/agi/issues/1113 -- I'm currently waiting for answers from Qualcomm for this issue.

Please feel free to re-open if you're facing issues validating S22 series

**Comment by ttanatb** [comment]
S22 is not listed on https://developer.android.com/agi/supported-devices yet, but we're building our testing infrastructure to be able to properly confirm that S22 (or other phones that launch with Android 12) works correctly with AGI

**Comment by tangobravo** [comment]
Ah, that's good to know - thanks. I've got the UK version so it's Exynos / Mali, but still seeing a validation error.
<img width="791" alt="Screenshot 2022-06-22 at 16 59 39" src="https://user-images.githubusercontent.com/770066/175078006-369d971e-9fc4-4562-b865-8fce774ebbfb.png">

**Comment by tangobravo** [comment]
I also picked up an A53 at the same time, which ships with Android 12 and has a Mali-G68 - that one passes validation 👍

**Comment by olehkuznetsov** [comment]
Fixed with 3.3.2
