### ISSUE TITLE
Question: frame profiler works for Desktop operating  systems?

### ISSUE THREAD

**Issue by jcortell68** [google/agi#1162]
Sorry for creating a github issue for a question, but I didn't find any mention of any sort of Discord/Slack/IIRC means to ask AGI questions. Is there one?

I noticed that when setting up for a _Frame Profile - Vulkan_ capture, the Device dropdown exposes an option for the host Windows device. The "A" in AGI is for Android, so I was surprised to see this. I also didn't find any mention of host support in https://developer.android.com/agi/frame-trace/frame-profiler

Can you speak to this? Does AGI in fact support frame profiling on desktop operating systems? If so, which ones? And by extension., could AGI be used (for frame profiling) of a device with Embedded Linux if the GPU/driver was supported?

**Comment by ttanatb** [comment]
Hi, thanks for your question! We don't have a community hub set up for questions yet, so you are welcome to file an issue just for a question. AGI is a fork of another project called GAPID, which was previously built to be platform agnostic. Since then, we've narrowed our use case to focus on Android devices. This means that AGI does not officially support profiling desktop apps -- this is not a user flow we test so we cannot ensure that things will work correctly, this is also not something we plan to support in the future. GAPID is also not in active development, so I would suggest seeking out a different tool for profiling desktop applications (i.e. RenderDoc for debugging, and a tool specific to the GPU vendor for profiling).

In fact, your host device _should not_ appear on the device drop-down. If you could provide a screenshot of your host device in the dropdown and the version of AGI you're using -- that'd be highly appreciated, thanks!

**Comment by jcortell68** [comment]
Thanks! Great answer. That clears things up for me.

Here's the screenshot. Note that it also says device support validation passed

![image](https://user-images.githubusercontent.com/109228283/181773128-c0dbbea9-293b-40bc-a47b-2bbed1b3f5c8.png)

**Comment by jcortell68** [comment]
Also note that the Application entry is from a previous Android capture.
