### ISSUE TITLE
Phone supported, but connected failed.

### ISSUE THREAD

**Issue by AstroWYH** [google/agi#1193]
**Environment information:**
 - AGI version:agi-3.0.1-windows.zip
 - Host OS: windows
 - Device model:OPPO Reno 6 Pro+
 - Android Version:11

**Bug description**
![image](https://user-images.githubusercontent.com/94472801/187610300-481b48eb-dd95-4c4c-a35a-87681f9322ef.png)
I find the website:https://developer.android.com/agi/supported-devices
OPPO Reno 6 Pro+ is supported, but it shows like above, and I could use adb to connect my phone normally in CMD, I don't know what's wrong, help me plz.

**Comment by rmsmelik** [comment]
Please check if you have USB debugging enabled (and press allow when connecting the phone to the computer). USB debugging is under development options.

**Comment by ttanatb** [comment]
Could you try this with our latest dev release? https://github.com/google/agi-dev-releases/releases/tag/v3.1.0-dev-20220830

This sounds like an issue that has been fixed in that release. Could you also upload the logs so it's easier for us to triage?From the help menu in the top left `Help > Open Log Directory` and upload `gapis.log` and `gapic.log`.
