### ISSUE TITLE
Support for Xiaomi Redmi Note 8 Pro

### ISSUE THREAD

**Issue by danierspo** [google/agi#1206]
**Environment information:**
 - AGI version: 2022-3.0.1:d7f82c3dda2df3d81e7b67157da8668c4242511c
 - Host OS: Windows 10 Home 21H2
 - Device model: Redmi Note 8 Pro (M1906G7G)
 - Android Version: 11 RP1A.200720.011

**Bug description**
Device support validation failed. Redmi Note 8 Pro comes with an ARM Mali G76 MC4 GPU, but unfortunately it is not about to receive an Android 12 update.

**Screenshots**
![AGI_Validation_failed](https://user-images.githubusercontent.com/56684426/188278749-c325c46d-4ddc-472b-935e-d567ce51d0cd.png)

My questions are:
1) Is it possible to add support for this device?
2) Is Samsung Galaxy A13, which comes with Android 12, supported?
3) Do all Android 12 devices support Game Mode API and interventions? About this topic, I read in the official docs that Game Mode are available on "select Android 12 devices" and on "devices running Android 13 or higher".

Your help would be appreciated, as I'm working on an university project about Android Game Development Kit.

**Comment by ttanatb** [comment]
Hi, thanks for reporting this issue. The error message seems to suggest that AGI is somehow unable to collect the GPU data from the device. I'm also unsure if the device itself will support GPU profiling (if the device is able to collect data and report the relevant information to tools like Perfetto or AGI). One of the initial steps that AGI runs in validation is to identify if the device supports GPU profiling via calling `adb shell getprop graphics.gpu.profiler.support` If this **does not** return `true` or `1`, then you can be certain that this device will not provide the information necessary for GPU profiling.

Note that even if `graphics.gpu.profiler.support` returns `true` there might still be another issue that causes the device to fail validation, but hopefully they've all been resolved by now.

I would also note that we have done some improvements to the validation process since the latest AGI release and our dev release can be found here https://github.com/google/agi-dev-releases/releases/tag/v3.2.0-dev-20220831 This provides more validation information for ease of debugging.

> Is Samsung Galaxy A13, which comes with Android 12, supported?

We don't have a definitive answer (it's up to the device to determine if it has enough memory to support GPU profiling), but you could try verifying with `adb shell getprop graphics.gpu.profiler.support` to identify if the device says that it supports GPU profiling. On Android 12 and beyond, if a device supports GPU profiling it should have the necessary data for tools like AGI & Perfetto.

> Do all Android 12 devices support Game Mode API and interventions? About this topic, I read in the official docs that Game Mode are available on "select Android 12 devices" and on "devices running Android 13 or higher".

It's a different team that owns this product but I can try to ask around for you

**Comment by danierspo** [comment]
Hi @ttanatb, thank you for your answer. Unfortunately, after executing `adb shell getprop graphics.gpu.profiler.support`, nothing but a blank line is returned; presumably, Redmi Note 8 Pro won't provide the information necessary for GPU profiling, as you stated.

Furthermore, I tried to use the v3.2.0-dev-20220831 release and validation generated the following log files:
[gapis.log](https://github.com/google/agi/files/9525334/gapis.log)
[gapic.log](https://github.com/google/agi/files/9525335/gapic.log)

An error is returned server-side for not being able to install AGI's apk; also, the UI gives the following error:
`Internal Error: com.google.gapid.server.Client$InternalServerErrorException: Package com.google.android.gapid.arm64v8a not found.`
I just think Redmi Note 8 Pro does not support AGI but, just for curiosity, can you explain the errors returned? Thanks a lot!

**Comment by dizcza** [comment]
Same happened to my Redmi Note 9T.

```
Internal Error: com.google.gapid.server.Client$InternalServerErrorException: Package com.google.android.gapid.arm64v8a not found.
```

and `adb shell getprop graphics.gpu.profiler.support` returns nothing.

**Comment by ttanatb** [comment]
When `adb shell getprop graphics.gpu.profiler.support` returns nothing, that means that this device is not capable of returning GPU profiling information. Without data from the device, AGI can't surface information that would be of use to GPU profiling on this device.
