### ISSUE TITLE
Samsung Device with Qualcomm GPU failing Validation

### ISSUE THREAD

**Issue by tgoulart** [google/agi#1252]
**Environment information:**
 - AGI version: 2022-3.3.0:dev-20221128-869d281c1bef8bdf853c20d9a90a07335779e51c
 - Host OS: macOS
 - Device model: Samsung S22 (SM-S901U1)
 - Android Version: 13

**Bug description**
Validation when preparing for a capture fails.

**Reproduction steps**
Run validation after selecting a device.

**Stacktrace**
N/A

**Screenshots**
![Screen Shot 2022-12-14 at 4 29 20 PM](https://user-images.githubusercontent.com/1531005/207744344-5740d04d-7378-489a-b040-d291795a4d1d.png)

**Additional debugging information**
- [gapis.log](https://github.com/google/agi/files/10232638/gapis.log)
- [gapic.log](https://github.com/google/agi/files/10232640/gapic.log)
- [logcat-full.txt](https://github.com/google/agi/files/10232670/logcat-full.txt)

**Comment by ttanatb** [comment]
Thanks for reporting this! This looks like a previous error that should've been fixed. Looking through the logcat I see `Adreno-GSL: <gsl_ldd_control:553>: ioctl fd 11 code 0xc018093b (IOCTL_KGSL_PERFCOUNTER_READ) failed: errno 1 Operation not permitted` which causes counter values to return 0 for everything. It would align with the error message you're getting because the error check that expects values to be `0` is passing and checks listed are expecting non-zero values.

This looks a lot like #1113 which is worrying because this was fixed in previous updates. Could you try running `adb shell "echo 1 > /sys/class/kgsl/kgsl-3d0/perfcounter"` to see if that fixes the issue? (AGI should be running this command for you) If you're getting permission errors, then could you provide the build number of your S22 here? (`Settings > Search for build number`)

**Comment by phx-ddevoe** [comment]
Hello, I am having this issue.
TP1A.220624.014.S901WVLU2BVK1

**Comment by tgoulart** [comment]
Thanks for the quick response. I came across that older issue before I reported this and tried that command before, but it failed with the permission error. 

My build number is: TP1A.220624.014.S901U1UEU2BVK1

**Comment by ttanatb** [comment]
It sounds like the write access has regressed to be root access not shell, and we're working with Samsung to get this fixed. In the meantime, if you are able to, you can root your phone as a workaround.

**Comment by ttanatb** [comment]
Issued the communication to Samsung and closing this for now because this issue is stale. If this issue persists, please re-open.

**Comment by JethroSovr** [comment]
I also get this error... my samsung s22+ is root access.  I connect usb to windows ,the device can not be searched, like the issue #1325 ,  connecte to the macos, it will be like this issue . Faild to validate.............. Dose anyone solved this problem ,plz show me the method.. thank you!
