### ISSUE TITLE
AGI validation fails in Samsung Tab s7+

### ISSUE THREAD

**Issue by RWVineeth** [google/agi#1253]
**Environment information:**
 - AGI version:Version 2022-3.2.1
 - Host OS: Windows
 If tracing on Android:
 - Device model: Samsung Tab s7+
 - Android Version:13

**Bug description**
The validation fails on the device. Validation starts, sample application runs and then it shows failed with the Screenshot attached

**Reproduction steps**
Steps to reproduce the behavior: Connect the device and start validation

**Stacktrace**
Please paste a stacktrace here if it's available.

**Screenshots**

**Additional debugging information**
- Please attach the generated _gapis.log_ and _gapic.log_ files you will find in the temp folder (e.g. /tmp/ on linux).
- If using Android: Please attach a full logcat dump (```adb logcat -d > logcat-f
 that contains logs since AGI was started. (log attached)
<img width="1205" alt="AGI_issue" src="https://user-images.githubusercontent.com/111271908/208436045-0eac8866-36ae-48a5-87ee-34f1b480e8d8.png">

[logcatagi.txt](https://github.com/google/agi/files/10259559/logcatagi.txt)

**Comment by ttanatb** [comment]
Thanks for reporting this! This looks like a previous error that should've been fixed. Looking through the logcat I see `Adreno-GSL: <gsl_ldd_control:553>: ioctl fd 11 code 0xc018093b (IOCTL_KGSL_PERFCOUNTER_READ) failed: errno 1 Operation not permitted` which causes counter values to return 0 for everything (which would cause validation to fail).

This looks a lot like https://github.com/google/agi/issues/1113 which is worrying because this was fixed in previous updates. Could you try running `adb shell "echo 1 > /sys/class/kgsl/kgsl-3d0/perfcounter"` to see if that fixes the issue? (AGI should be running this command for you) If you're getting permission errors, then could you provide the build number of your S22 here? (Settings > Search for build number)

**Comment by RWVineeth** [comment]
Hey,
I'm getting permission error
The build number is TP1A.220624.014.T970XXU2DVK3

**Comment by ttanatb** [comment]
I'm closing this issue as a duplicate to #1252 

It sounds like the write access has regressed to be root access not shell, and we're working with Samsung to get this fixed. In the meantime, if you are able to, you can root your phone as a workaround.
