### ISSUE TITLE
Failed to validate the trace of the sample application with the Mali validator

### ISSUE THREAD

**Issue by HuiOpenSource** [google/agi#1292]
**Environment information:**
 - AGI version:
 - Host OS: [e.g. Linux]
 If tracing on Android:
 - Device model:
 - Android Version:

**Bug description**

**Reproduction steps**

**Stacktrace**
Please paste a stacktrace here if it's available.

**Screenshots**

**Additional debugging information**
- Please attach the generated _gapis.log_ and _gapic.log_ files you will find in the temp folder (e.g. /tmp/ on linux).
- If using Android: Please attach a full logcat dump (```adb logcat -d > logcat-full.txt```) that contains logs since AGI was started.

**Comment by ttanatb** [comment]
There isn't enough information to really triage the issue here. This looks like it could be a similar issue that was recently fixed. Please try the new release https://github.com/google/agi-dev-releases/releases/tag/v3.3.1-dev-20230607 and re-open this (with more information, such as screenshots, logs, and trace) if you're still running into this problem.
