### ISSUE TITLE
Not able to capture GPU frequency

### ISSUE THREAD

**Issue by ylz-at** [google/agi#755]
**Environment information:**
 - AGI version: Version 1.1.0:dev-20210318-0a20e55844baeb58bb29fe8dd58a004a656efcd5
 - Host OS: Windows
 If tracing on Android:
 - Device model: samsung SM-G9730
 - Android Version: Android 11

**Bug description**
I need to monitor the GPU frequency, but not show up in the result.
I should be able to see the result of GPU frequency, as ftrace_events: "power/gpu_frequency" is included in the data source.

**Reproduction steps**
File->Capture Trace->Trace Options->Profile Config: Custom Configure

Update the custom configure to 

```
buffers {
  size_kb: 131072
  fill_policy: DISCARD
}
buffers {
  size_kb: 4096
  fill_policy: DISCARD
}
data_sources {
  config {
    name: "linux.ftrace"
    ftrace_config {
      ftrace_events: "sched/sched_process_free"
      ftrace_events: "task/task_newtask"
      ftrace_events: "task/task_rename"
      ftrace_events: "power/gpu_frequency"
      ftrace_events: "gpu_mem/gpu_mem_total"
      buffer_size_kb: 8192
      drain_period_ms: 250
      compact_sched {
        enabled: true
      }
    }
  }
}
data_sources {
  config {
    name: "linux.process_stats"
    target_buffer: 1
    process_stats_config {
      scan_all_processes_on_start: true
    }
  }
}
data_sources {
  config {
    name: "linux.process_stats"
    process_stats_config {
      proc_stats_poll_ms: 2000
      proc_stats_cache_ttl_ms: 20000
    }
  }
}
data_sources {
  config {
    name: "gpu.renderstages"
  }
}
data_sources {
  config {
    name: "VulkanAPI"
  }
}
data_sources {
  config {
    name: "android.surfaceflinger.frame"
  }
}
write_into_file: true
file_write_period_ms: 2000
max_file_size_bytes: 2147483648
flush_period_ms: 5000

```

**Stacktrace**
Please paste a stacktrace here if it's available.

**Screenshots**

**Additional debugging information**
- Please attach the generated _gapis.log_ and _gapic.log_ files you will find in the temp folder (e.g. /tmp/ on linux).
- If using Android: Please attach a full logcat dump (```adb logcat -d > logcat-full.txt```) that contains logs since AGI was started.

**Comment by hevrard** [comment]
That's because the GPU frequency information is provided by a GPU counter, not ftrace, so the data source you want is something like:

```
data_sources {
  config {
    name: "gpu.counters"
    gpu_counter_config {
      counter_period_ns: 1000000
      counter_ids: 155    ### This ID might be different depending on the device / driver version
    }
  }
}
```

I don't have an SM-G9730 at hand, but on my Pixel4XL (also Adreno GPU), this config is enough to get GPU frequency:

```
buffers {
  size_kb: 131072
  fill_policy: DISCARD
}
buffers {
  size_kb: 4096
  fill_policy: DISCARD
}
data_sources {
  config {
    name: "gpu.counters"
    gpu_counter_config {
      counter_period_ns: 1000000
      counter_ids: 155
    }
  }
}
write_into_file: true
file_write_period_ms: 2000
max_file_size_bytes: 2147483648
flush_period_ms: 5000
```

In general, we recommend to use the UI to select profiling data. I found the GPU frequency counter ID by selecting only this one in the UI, and after that looking at the generated config in the "Advanced Mode" option.

More generally, GPU counters details are reported by the device GPU driver, so they may change between devices and even between GPU driver updates. AGI takes care of querying the available GPU counters, and the UI offers a nice way to list and select the ones you want to see.

I hope this helps, feel free to reopen if you're still failing to get GPU frequency on your device.
